/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.9.4.0 (NJsonSchema v10.3.1.0 (Newtonsoft.Json v12.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming

import axios, { AxiosError, AxiosInstance, AxiosRequestConfig, AxiosResponse, CancelToken } from 'axios';

export class CategoryClient {
    private instance: AxiosInstance;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {
        this.instance = instance ? instance : axios.create();
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    getCategoryList(  cancelToken?: CancelToken | undefined): Promise<CategoryVm> {
        let url_ = this.baseUrl + "/Category/getCategory";
        url_ = url_.replace(/[?&]$/, "");

        let options_ = <AxiosRequestConfig>{
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetCategoryList(_response);
        });
    }

    protected processGetCategoryList(response: AxiosResponse): Promise<CategoryVm> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = CategoryVm.fromJS(resultData200);
            return result200;
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<CategoryVm>(<any>null);
    }

    get(  cancelToken?: CancelToken | undefined): Promise<TreeItemOfCategoryDto[]> {
        let url_ = this.baseUrl + "/Category/getCategoryTree";
        url_ = url_.replace(/[?&]$/, "");

        let options_ = <AxiosRequestConfig>{
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGet(_response);
        });
    }

    protected processGet(response: AxiosResponse): Promise<TreeItemOfCategoryDto[]> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(TreeItemOfCategoryDto.fromJS(item));
            }
            return result200;
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<TreeItemOfCategoryDto[]>(<any>null);
    }

    create(name: string | null | undefined, farsiName: string | null | undefined, imageContent: FileParameter | null | undefined, parentId: number | undefined, specifications: string | null | undefined , cancelToken?: CancelToken | undefined): Promise<number> {
        let url_ = this.baseUrl + "/Category";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = new FormData();
        if (name !== null && name !== undefined)
            content_.append("Name", name.toString());
        if (farsiName !== null && farsiName !== undefined)
            content_.append("FarsiName", farsiName.toString());
        if (imageContent !== null && imageContent !== undefined)
            content_.append("ImageContent", imageContent.data, imageContent.fileName ? imageContent.fileName : "ImageContent");
        if (parentId === null || parentId === undefined)
            throw new Error("The parameter 'parentId' cannot be null.");
        else
            content_.append("ParentId", parentId.toString());
        if (specifications !== null && specifications !== undefined)
            content_.append("Specifications", specifications.toString());

        let options_ = <AxiosRequestConfig>{
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processCreate(_response);
        });
    }

    protected processCreate(response: AxiosResponse): Promise<number> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = resultData200 !== undefined ? resultData200 : <any>null;
            return result200;
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<number>(<any>null);
    }
}

export class ProductClient {
    private instance: AxiosInstance;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {
        this.instance = instance ? instance : axios.create();
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    get(  cancelToken?: CancelToken | undefined): Promise<ProductVm> {
        let url_ = this.baseUrl + "/Product";
        url_ = url_.replace(/[?&]$/, "");

        let options_ = <AxiosRequestConfig>{
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGet(_response);
        });
    }

    protected processGet(response: AxiosResponse): Promise<ProductVm> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = ProductVm.fromJS(resultData200);
            return result200;
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ProductVm>(<any>null);
    }

    create(brandName: string | null | undefined, description: string | null | undefined, shortDescription: string | null | undefined, name: string | null | undefined, farsiName: string | null | undefined, price: number | undefined, image: FileParameter | null | undefined, productSpecifications: string | null | undefined, categoryId: number | undefined , cancelToken?: CancelToken | undefined): Promise<number> {
        let url_ = this.baseUrl + "/Product";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = new FormData();
        if (brandName !== null && brandName !== undefined)
            content_.append("BrandName", brandName.toString());
        if (description !== null && description !== undefined)
            content_.append("Description", description.toString());
        if (shortDescription !== null && shortDescription !== undefined)
            content_.append("ShortDescription", shortDescription.toString());
        if (name !== null && name !== undefined)
            content_.append("Name", name.toString());
        if (farsiName !== null && farsiName !== undefined)
            content_.append("FarsiName", farsiName.toString());
        if (price === null || price === undefined)
            throw new Error("The parameter 'price' cannot be null.");
        else
            content_.append("Price", price.toString());
        if (image !== null && image !== undefined)
            content_.append("Image", image.data, image.fileName ? image.fileName : "Image");
        if (productSpecifications !== null && productSpecifications !== undefined)
            content_.append("ProductSpecifications", productSpecifications.toString());
        if (categoryId === null || categoryId === undefined)
            throw new Error("The parameter 'categoryId' cannot be null.");
        else
            content_.append("CategoryId", categoryId.toString());

        let options_ = <AxiosRequestConfig>{
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processCreate(_response);
        });
    }

    protected processCreate(response: AxiosResponse): Promise<number> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = resultData200 !== undefined ? resultData200 : <any>null;
            return result200;
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<number>(<any>null);
    }
}

export class ShoppingCartClient {
    private instance: AxiosInstance;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {
        this.instance = instance ? instance : axios.create();
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    getCartProductList(  cancelToken?: CancelToken | undefined): Promise<CartProductVm> {
        let url_ = this.baseUrl + "/ShoppingCart/GetCartProductList";
        url_ = url_.replace(/[?&]$/, "");

        let options_ = <AxiosRequestConfig>{
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetCartProductList(_response);
        });
    }

    protected processGetCartProductList(response: AxiosResponse): Promise<CartProductVm> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = CartProductVm.fromJS(resultData200);
            return result200;
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<CartProductVm>(<any>null);
    }

    create(command: CreateCartProductCommand , cancelToken?: CancelToken | undefined): Promise<number> {
        let url_ = this.baseUrl + "/ShoppingCart/createCartProduct";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(command);

        let options_ = <AxiosRequestConfig>{
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processCreate(_response);
        });
    }

    protected processCreate(response: AxiosResponse): Promise<number> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = resultData200 !== undefined ? resultData200 : <any>null;
            return result200;
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<number>(<any>null);
    }

    delete(command: DeleteCartProductCommand , cancelToken?: CancelToken | undefined): Promise<Unit> {
        let url_ = this.baseUrl + "/ShoppingCart/deleteCartProduct";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(command);

        let options_ = <AxiosRequestConfig>{
            data: content_,
            method: "DELETE",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processDelete(_response);
        });
    }

    protected processDelete(response: AxiosResponse): Promise<Unit> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = Unit.fromJS(resultData200);
            return result200;
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<Unit>(<any>null);
    }
}

export class CategoryVm implements ICategoryVm {
    categoryDtos?: CategoryDto[] | undefined;

    constructor(data?: ICategoryVm) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["categoryDtos"])) {
                this.categoryDtos = [] as any;
                for (let item of _data["categoryDtos"])
                    this.categoryDtos!.push(CategoryDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): CategoryVm {
        data = typeof data === 'object' ? data : {};
        let result = new CategoryVm();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.categoryDtos)) {
            data["categoryDtos"] = [];
            for (let item of this.categoryDtos)
                data["categoryDtos"].push(item.toJSON());
        }
        return data; 
    }
}

export interface ICategoryVm {
    categoryDtos?: CategoryDto[] | undefined;
}

export class CategoryDto implements ICategoryDto {
    id?: number;
    name?: string | undefined;
    farsiName?: string | undefined;
    image?: string | undefined;
    content?: string | undefined;
    parentId?: number | undefined;
    specifications?: Specification[] | undefined;

    constructor(data?: ICategoryDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
            this.farsiName = _data["farsiName"];
            this.image = _data["image"];
            this.content = _data["content"];
            this.parentId = _data["parentId"];
            if (Array.isArray(_data["specifications"])) {
                this.specifications = [] as any;
                for (let item of _data["specifications"])
                    this.specifications!.push(Specification.fromJS(item));
            }
        }
    }

    static fromJS(data: any): CategoryDto {
        data = typeof data === 'object' ? data : {};
        let result = new CategoryDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        data["farsiName"] = this.farsiName;
        data["image"] = this.image;
        data["content"] = this.content;
        data["parentId"] = this.parentId;
        if (Array.isArray(this.specifications)) {
            data["specifications"] = [];
            for (let item of this.specifications)
                data["specifications"].push(item.toJSON());
        }
        return data; 
    }
}

export interface ICategoryDto {
    id?: number;
    name?: string | undefined;
    farsiName?: string | undefined;
    image?: string | undefined;
    content?: string | undefined;
    parentId?: number | undefined;
    specifications?: Specification[] | undefined;
}

export class Specification implements ISpecification {
    id?: number;
    specificationKey?: string | undefined;
    categoryId?: number;
    category?: Category | undefined;
    productSpecifications?: ProductSpecification[] | undefined;

    constructor(data?: ISpecification) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.specificationKey = _data["specificationKey"];
            this.categoryId = _data["categoryId"];
            this.category = _data["category"] ? Category.fromJS(_data["category"]) : <any>undefined;
            if (Array.isArray(_data["productSpecifications"])) {
                this.productSpecifications = [] as any;
                for (let item of _data["productSpecifications"])
                    this.productSpecifications!.push(ProductSpecification.fromJS(item));
            }
        }
    }

    static fromJS(data: any): Specification {
        data = typeof data === 'object' ? data : {};
        let result = new Specification();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["specificationKey"] = this.specificationKey;
        data["categoryId"] = this.categoryId;
        data["category"] = this.category ? this.category.toJSON() : <any>undefined;
        if (Array.isArray(this.productSpecifications)) {
            data["productSpecifications"] = [];
            for (let item of this.productSpecifications)
                data["productSpecifications"].push(item.toJSON());
        }
        return data; 
    }
}

export interface ISpecification {
    id?: number;
    specificationKey?: string | undefined;
    categoryId?: number;
    category?: Category | undefined;
    productSpecifications?: ProductSpecification[] | undefined;
}

export class Category implements ICategory {
    id?: number;
    name?: string | undefined;
    farsiName?: string | undefined;
    image?: string | undefined;
    parentId?: number;
    content?: string | undefined;
    productCategories?: ProductCategory[] | undefined;
    specifications?: Specification[] | undefined;

    constructor(data?: ICategory) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
            this.farsiName = _data["farsiName"];
            this.image = _data["image"];
            this.parentId = _data["parentId"];
            this.content = _data["content"];
            if (Array.isArray(_data["productCategories"])) {
                this.productCategories = [] as any;
                for (let item of _data["productCategories"])
                    this.productCategories!.push(ProductCategory.fromJS(item));
            }
            if (Array.isArray(_data["specifications"])) {
                this.specifications = [] as any;
                for (let item of _data["specifications"])
                    this.specifications!.push(Specification.fromJS(item));
            }
        }
    }

    static fromJS(data: any): Category {
        data = typeof data === 'object' ? data : {};
        let result = new Category();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        data["farsiName"] = this.farsiName;
        data["image"] = this.image;
        data["parentId"] = this.parentId;
        data["content"] = this.content;
        if (Array.isArray(this.productCategories)) {
            data["productCategories"] = [];
            for (let item of this.productCategories)
                data["productCategories"].push(item.toJSON());
        }
        if (Array.isArray(this.specifications)) {
            data["specifications"] = [];
            for (let item of this.specifications)
                data["specifications"].push(item.toJSON());
        }
        return data; 
    }
}

export interface ICategory {
    id?: number;
    name?: string | undefined;
    farsiName?: string | undefined;
    image?: string | undefined;
    parentId?: number;
    content?: string | undefined;
    productCategories?: ProductCategory[] | undefined;
    specifications?: Specification[] | undefined;
}

export class ProductCategory implements IProductCategory {
    id?: number;
    productId?: number;
    categoryId?: number;
    product?: Product | undefined;
    category?: Category | undefined;

    constructor(data?: IProductCategory) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.productId = _data["productId"];
            this.categoryId = _data["categoryId"];
            this.product = _data["product"] ? Product.fromJS(_data["product"]) : <any>undefined;
            this.category = _data["category"] ? Category.fromJS(_data["category"]) : <any>undefined;
        }
    }

    static fromJS(data: any): ProductCategory {
        data = typeof data === 'object' ? data : {};
        let result = new ProductCategory();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["productId"] = this.productId;
        data["categoryId"] = this.categoryId;
        data["product"] = this.product ? this.product.toJSON() : <any>undefined;
        data["category"] = this.category ? this.category.toJSON() : <any>undefined;
        return data; 
    }
}

export interface IProductCategory {
    id?: number;
    productId?: number;
    categoryId?: number;
    product?: Product | undefined;
    category?: Category | undefined;
}

export class Product implements IProduct {
    id?: number;
    brandName?: string | undefined;
    description?: string | undefined;
    shortDescription?: string | undefined;
    name?: string | undefined;
    farsiName?: string | undefined;
    price?: number;
    image?: string | undefined;
    cartProducts?: CartProduct[] | undefined;
    productSpecifications?: ProductSpecification[] | undefined;
    productCategories?: ProductCategory[] | undefined;

    constructor(data?: IProduct) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.brandName = _data["brandName"];
            this.description = _data["description"];
            this.shortDescription = _data["shortDescription"];
            this.name = _data["name"];
            this.farsiName = _data["farsiName"];
            this.price = _data["price"];
            this.image = _data["image"];
            if (Array.isArray(_data["cartProducts"])) {
                this.cartProducts = [] as any;
                for (let item of _data["cartProducts"])
                    this.cartProducts!.push(CartProduct.fromJS(item));
            }
            if (Array.isArray(_data["productSpecifications"])) {
                this.productSpecifications = [] as any;
                for (let item of _data["productSpecifications"])
                    this.productSpecifications!.push(ProductSpecification.fromJS(item));
            }
            if (Array.isArray(_data["productCategories"])) {
                this.productCategories = [] as any;
                for (let item of _data["productCategories"])
                    this.productCategories!.push(ProductCategory.fromJS(item));
            }
        }
    }

    static fromJS(data: any): Product {
        data = typeof data === 'object' ? data : {};
        let result = new Product();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["brandName"] = this.brandName;
        data["description"] = this.description;
        data["shortDescription"] = this.shortDescription;
        data["name"] = this.name;
        data["farsiName"] = this.farsiName;
        data["price"] = this.price;
        data["image"] = this.image;
        if (Array.isArray(this.cartProducts)) {
            data["cartProducts"] = [];
            for (let item of this.cartProducts)
                data["cartProducts"].push(item.toJSON());
        }
        if (Array.isArray(this.productSpecifications)) {
            data["productSpecifications"] = [];
            for (let item of this.productSpecifications)
                data["productSpecifications"].push(item.toJSON());
        }
        if (Array.isArray(this.productCategories)) {
            data["productCategories"] = [];
            for (let item of this.productCategories)
                data["productCategories"].push(item.toJSON());
        }
        return data; 
    }
}

export interface IProduct {
    id?: number;
    brandName?: string | undefined;
    description?: string | undefined;
    shortDescription?: string | undefined;
    name?: string | undefined;
    farsiName?: string | undefined;
    price?: number;
    image?: string | undefined;
    cartProducts?: CartProduct[] | undefined;
    productSpecifications?: ProductSpecification[] | undefined;
    productCategories?: ProductCategory[] | undefined;
}

export class CartProduct implements ICartProduct {
    id?: number;
    amount?: number;
    productId?: number;
    product?: Product | undefined;

    constructor(data?: ICartProduct) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.amount = _data["amount"];
            this.productId = _data["productId"];
            this.product = _data["product"] ? Product.fromJS(_data["product"]) : <any>undefined;
        }
    }

    static fromJS(data: any): CartProduct {
        data = typeof data === 'object' ? data : {};
        let result = new CartProduct();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["amount"] = this.amount;
        data["productId"] = this.productId;
        data["product"] = this.product ? this.product.toJSON() : <any>undefined;
        return data; 
    }
}

export interface ICartProduct {
    id?: number;
    amount?: number;
    productId?: number;
    product?: Product | undefined;
}

export class ProductSpecification implements IProductSpecification {
    id?: number;
    specificationId?: number;
    specification?: Specification | undefined;
    productId?: number;
    product?: Product | undefined;
    specificationValue?: string | undefined;

    constructor(data?: IProductSpecification) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.specificationId = _data["specificationId"];
            this.specification = _data["specification"] ? Specification.fromJS(_data["specification"]) : <any>undefined;
            this.productId = _data["productId"];
            this.product = _data["product"] ? Product.fromJS(_data["product"]) : <any>undefined;
            this.specificationValue = _data["specificationValue"];
        }
    }

    static fromJS(data: any): ProductSpecification {
        data = typeof data === 'object' ? data : {};
        let result = new ProductSpecification();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["specificationId"] = this.specificationId;
        data["specification"] = this.specification ? this.specification.toJSON() : <any>undefined;
        data["productId"] = this.productId;
        data["product"] = this.product ? this.product.toJSON() : <any>undefined;
        data["specificationValue"] = this.specificationValue;
        return data; 
    }
}

export interface IProductSpecification {
    id?: number;
    specificationId?: number;
    specification?: Specification | undefined;
    productId?: number;
    product?: Product | undefined;
    specificationValue?: string | undefined;
}

export class TreeItemOfCategoryDto implements ITreeItemOfCategoryDto {
    item?: CategoryDto | undefined;
    children?: TreeItemOfCategoryDto[] | undefined;

    constructor(data?: ITreeItemOfCategoryDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.item = _data["item"] ? CategoryDto.fromJS(_data["item"]) : <any>undefined;
            if (Array.isArray(_data["children"])) {
                this.children = [] as any;
                for (let item of _data["children"])
                    this.children!.push(TreeItemOfCategoryDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): TreeItemOfCategoryDto {
        data = typeof data === 'object' ? data : {};
        let result = new TreeItemOfCategoryDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["item"] = this.item ? this.item.toJSON() : <any>undefined;
        if (Array.isArray(this.children)) {
            data["children"] = [];
            for (let item of this.children)
                data["children"].push(item.toJSON());
        }
        return data; 
    }
}

export interface ITreeItemOfCategoryDto {
    item?: CategoryDto | undefined;
    children?: TreeItemOfCategoryDto[] | undefined;
}

export class ProductVm implements IProductVm {
    productDtos?: ProductDto[] | undefined;

    constructor(data?: IProductVm) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["productDtos"])) {
                this.productDtos = [] as any;
                for (let item of _data["productDtos"])
                    this.productDtos!.push(ProductDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): ProductVm {
        data = typeof data === 'object' ? data : {};
        let result = new ProductVm();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.productDtos)) {
            data["productDtos"] = [];
            for (let item of this.productDtos)
                data["productDtos"].push(item.toJSON());
        }
        return data; 
    }
}

export interface IProductVm {
    productDtos?: ProductDto[] | undefined;
}

export class ProductDto implements IProductDto {
    id?: number;
    brandName?: string | undefined;
    description?: string | undefined;
    shortDescription?: string | undefined;
    name?: string | undefined;
    farsiName?: string | undefined;
    price?: number;
    image?: string | undefined;
    categoryName?: string | undefined;
    categoryId?: number;

    constructor(data?: IProductDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.brandName = _data["brandName"];
            this.description = _data["description"];
            this.shortDescription = _data["shortDescription"];
            this.name = _data["name"];
            this.farsiName = _data["farsiName"];
            this.price = _data["price"];
            this.image = _data["image"];
            this.categoryName = _data["categoryName"];
            this.categoryId = _data["categoryId"];
        }
    }

    static fromJS(data: any): ProductDto {
        data = typeof data === 'object' ? data : {};
        let result = new ProductDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["brandName"] = this.brandName;
        data["description"] = this.description;
        data["shortDescription"] = this.shortDescription;
        data["name"] = this.name;
        data["farsiName"] = this.farsiName;
        data["price"] = this.price;
        data["image"] = this.image;
        data["categoryName"] = this.categoryName;
        data["categoryId"] = this.categoryId;
        return data; 
    }
}

export interface IProductDto {
    id?: number;
    brandName?: string | undefined;
    description?: string | undefined;
    shortDescription?: string | undefined;
    name?: string | undefined;
    farsiName?: string | undefined;
    price?: number;
    image?: string | undefined;
    categoryName?: string | undefined;
    categoryId?: number;
}

export class CartProductVm implements ICartProductVm {
    cartProductDtos?: CartProductDto[] | undefined;

    constructor(data?: ICartProductVm) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["cartProductDtos"])) {
                this.cartProductDtos = [] as any;
                for (let item of _data["cartProductDtos"])
                    this.cartProductDtos!.push(CartProductDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): CartProductVm {
        data = typeof data === 'object' ? data : {};
        let result = new CartProductVm();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.cartProductDtos)) {
            data["cartProductDtos"] = [];
            for (let item of this.cartProductDtos)
                data["cartProductDtos"].push(item.toJSON());
        }
        return data; 
    }
}

export interface ICartProductVm {
    cartProductDtos?: CartProductDto[] | undefined;
}

export class CartProductDto implements ICartProductDto {
    id?: number;
    amount?: number;
    productId?: number;
    brandName?: string | undefined;
    description?: string | undefined;
    shortDescription?: string | undefined;
    name?: string | undefined;
    farsiName?: string | undefined;
    price?: number;
    image?: string | undefined;

    constructor(data?: ICartProductDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.amount = _data["amount"];
            this.productId = _data["productId"];
            this.brandName = _data["brandName"];
            this.description = _data["description"];
            this.shortDescription = _data["shortDescription"];
            this.name = _data["name"];
            this.farsiName = _data["farsiName"];
            this.price = _data["price"];
            this.image = _data["image"];
        }
    }

    static fromJS(data: any): CartProductDto {
        data = typeof data === 'object' ? data : {};
        let result = new CartProductDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["amount"] = this.amount;
        data["productId"] = this.productId;
        data["brandName"] = this.brandName;
        data["description"] = this.description;
        data["shortDescription"] = this.shortDescription;
        data["name"] = this.name;
        data["farsiName"] = this.farsiName;
        data["price"] = this.price;
        data["image"] = this.image;
        return data; 
    }
}

export interface ICartProductDto {
    id?: number;
    amount?: number;
    productId?: number;
    brandName?: string | undefined;
    description?: string | undefined;
    shortDescription?: string | undefined;
    name?: string | undefined;
    farsiName?: string | undefined;
    price?: number;
    image?: string | undefined;
}

export class CreateCartProductCommand implements ICreateCartProductCommand {
    amount?: number;
    productId?: number;

    constructor(data?: ICreateCartProductCommand) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.amount = _data["amount"];
            this.productId = _data["productId"];
        }
    }

    static fromJS(data: any): CreateCartProductCommand {
        data = typeof data === 'object' ? data : {};
        let result = new CreateCartProductCommand();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["amount"] = this.amount;
        data["productId"] = this.productId;
        return data; 
    }
}

export interface ICreateCartProductCommand {
    amount?: number;
    productId?: number;
}

export class Unit implements IUnit {

    constructor(data?: IUnit) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
    }

    static fromJS(data: any): Unit {
        data = typeof data === 'object' ? data : {};
        let result = new Unit();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        return data; 
    }
}

export interface IUnit {
}

export class DeleteCartProductCommand implements IDeleteCartProductCommand {
    id?: number;

    constructor(data?: IDeleteCartProductCommand) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
        }
    }

    static fromJS(data: any): DeleteCartProductCommand {
        data = typeof data === 'object' ? data : {};
        let result = new DeleteCartProductCommand();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        return data; 
    }
}

export interface IDeleteCartProductCommand {
    id?: number;
}

export interface FileParameter {
    data: any;
    fileName: string;
}

export class ApiException extends Error {
    message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}

function isAxiosError(obj: any | undefined): obj is AxiosError {
    return obj && obj.isAxiosError === true;
}