export const productCategories = [
  {
    id: 1,
    parentId: 0,
    categoryName: "fashion",
    name: "مد و پوشاک",
    image: "images/sweatshirt.jpg",
    midCat: true,
  },
  {
    id: 10,
    parentId: 1,
    categoryName: "men",
    name: "مردانه",
    image: "images/sweatshirt.jpg",
    midCat: true,
  },
  {
    id: 11,
    parentId: 1,
    categoryName: "women",
    name: "زنانه",
    image: "images/sweatshirt.jpg",
    midCat: true,
  },
  {
    id: 12,
    parentId: 1,
    categoryName: "kids",
    name: "بچه گانه",
    image: "images/sweatshirt.jpg",
    midCat: true,
  },
  {
    id: 20,
    parentId: 10,
    categoryName: "men-pants",
    name: "شلوار",
    image: "images/pant.jpg",
    midCat: false,
  },
  {
    id: 301,
    parentId: 20,
    categoryName: "men-pants-casual",
    name: "شلوار راحتی",
    image: "images/pant.jpg",
    midCat: false,
  },
  {
    id: 302,
    parentId: 20,
    categoryName: "men-pants-cotton",
    name: "شلوار کتان",
    image: "images/pant.jpg",
    midCat: false,
  },
  {
    id: 21,
    parentId: 10,
    categoryName: "men-socks",
    name: "جوراب",
    image: "images/socks.jpg",
    midCat: false,
  },
  {
    id: 303,
    parentId: 21,
    categoryName: "men-socks-nakhi",
    name: "جوراب نخی",
    image: "images/socks.jpg",
    midCat: false,
  },
  {
    id: 304,
    parentId: 21,
    categoryName: "men-socks-tarhdar",
    name: "جوراب طرح دار",
    image: "images/socks.jpg",
    midCat: false,
  },
  {
    id: 22,
    parentId: 10,
    categoryName: "men-shoes",
    name: "کفش",
    image: "images/shoes.jpg",
    midCat: false,
  },
  {
    id: 305,
    parentId: 22,
    categoryName: "men-shoes-sport",
    name: "کفش ورزشی",
    image: "images/shoes.jpg",
    midCat: false,
  },
  {
    id: 306,
    parentId: 22,
    categoryName: "men-shoes-edari",
    name: "کفش اداری",
    image: "images/shoes.jpg",
    midCat: false,
  },
  {
    id: 23,
    parentId: 10,
    categoryName: "men-sweatshirt",
    name: "گرم کن",
    image: "images/sweatshirt.jpg",
    midCat: false,
  },
  {
    id: 24,
    parentId: 11,
    categoryName: "women-manto",
    name: "مانتو",
    image: "images/sweatshirt.jpg",
    midCat: false,
  },
  {
    id: 307,
    parentId: 24,
    categoryName: "women-manto-sonati",
    name: "مانتو سنتی",
    image: "images/sweatshirt.jpg",
    midCat: false,
  },
  {
    id: 308,
    parentId: 24,
    categoryName: "women-manto-majlesi",
    name: "مانتو مجلسی",
    image: "images/sweatshirt.jpg",
    midCat: false,
  },
  {
    id: 309,
    parentId: 24,
    categoryName: "women-manto-sport",
    name: "مانتو ورزشی",
    image: "images/sweatshirt.jpg",
    midCat: false,
  },
  {
    id: 25,
    parentId: 11,
    categoryName: "women-shoes",
    name: "کفش",
    image: "images/sweatshirt.jpg",
    midCat: true,
  },
  {
    id: 201,
    parentId: 25,
    categoryName: "high-heels",
    name: "کفش پاشنه بلند",
    image: "images/sweatshirt.jpg",
    midCat: false,
  },
  {
    id: 202,
    parentId: 25,
    categoryName: "flat-shoes",
    name: "کفش راحتی",
    image: "images/sweatshirt.jpg",
    midCat: false,
  },
  {
    id: 26,
    parentId: 11,
    categoryName: "women-scarf",
    name: "روسری",
    image: "images/sweatshirt.jpg",
    midCat: false,
  },
  {
    id: 27,
    parentId: 11,
    categoryName: "women-skirt",
    name: "دامن",
    image: "images/sweatshirt.jpg",
    midCat: true,
  },
  {
    id: 101,
    parentId: 27,
    categoryName: "women-skirt-monokrom",
    name: "دامن ساده",
    image: "images/sweatshirt.jpg",
    midCat: false,
  },
  {
    id: 102,
    parentId: 27,
    categoryName: "women-skirt-colorful",
    name: "دامن طرح دار",
    image: "images/sweatshirt.jpg",
    midCat: false,
  },
  {
    id: 28,
    parentId: 12,
    categoryName: "kids-kapshen",
    name: "کاپشن",
    image: "images/sweatshirt.jpg",
    midCat: false,
  },
  {
    id: 29,
    parentId: 12,
    categoryName: "kids-sport-set",
    name: "لباس ورزشی",
    image: "images/sweatshirt.jpg",
    midCat: false,
  },
  {
    id: 30,
    parentId: 12,
    categoryName: "kids-socks",
    name: "جوراب",
    image: "images/sweatshirt.jpg",
    midCat: false,
  },
  {
    id: 31,
    parentId: 12,
    categoryName: "kids-shirt",
    name: "بلوز",
    image: "images/sweatshirt.jpg",
    midCat: false,
  },
];

export const products = [
  {
    id: 1,
    brandName: "Adidas",
    shortDescription: "ست گرم کن آدیداس",specifics:[{key:"طرح",value:"سینایی"},{key:"کشور",value:"ایران"}],
    description:
      "در تولید این محصول از الیاف با کیفیت استفاده شده است و بهترین طراحان در طراحی آن دست داشته اند، در سه سایز ارائه شده است.",
    enName: "pant_2r_33_Q",
    categoryNames: ["men-pants-casual", "men-pants", "men", "fashion"],
    name: "شلوار تبان",
    price: 10000,
    image: "/images/shoes.jpg",
    address: "/productdetail",
  },
  {
    id: 2,
    brandName: "Kikiriki",
    shortDescription: "ست گرم کن آدیداس",specifics:[{key:"طرح",value:"سینایی"},{key:"کشور",value:"ایران"}],
    description:
      "در تولید این محصول از الیاف با کیفیت استفاده شده است و بهترین طراحان در طراحی آن دست داشته اند، در سه سایز ارائه شده است.",
    enName: "pant_2r_33_Q",
    categoryNames: ["men-pants-cotton", "men-pants", "men", "fashion"],
    name: "شلوار تبان",
    price: 10000,
    image: "/images/shoes.jpg",
    address: "/productdetail",
  },
  {
    id: 3,
    brandName: "Mel&Moj",
    shortDescription: "ست گرم کن آدیداس",specifics:[{key:"طرح",value:"سینایی"},{key:"کشور",value:"ایران"}],
    description:
      "در تولید این محصول از الیاف با کیفیت استفاده شده است و بهترین طراحان در طراحی آن دست داشته اند، در سه سایز ارائه شده است.",
    enName: "pant_2r_33_Q",
    categoryNames: ["men-socks-nakhi", "men-socks", "men", "fashion"],
    name: "جوراب کویر",
    price: 10000,
    image: "/images/pant.jpg",
    address: "/productdetail",
  },
  {
    id: 4,
    brandName: "Kikiriki",
    shortDescription: "ست گرم کن آدیداس",specifics:[{key:"طرح",value:"سینایی"},{key:"کشور",value:"ایران"}],
    description:
      "در تولید این محصول از الیاف با کیفیت استفاده شده است و بهترین طراحان در طراحی آن دست داشته اند، در سه سایز ارائه شده است.",
    enName: "pant_2r_33_Q",
    categoryNames: ["men-socks-tarhdar", "men-socks", "men", "fashion"],
    name: "جوراب کویر",
    price: 10000,
    image: "/images/shoes.jpg",
    address: "/productdetail",
  },
  {
    id: 6,
    brandName: "Adidas",
    shortDescription: "ست گرم کن آدیداس",specifics:[{key:"طرح",value:"سینایی"},{key:"کشور",value:"ایران"}],
    description:
      "در تولید این محصول از الیاف با کیفیت استفاده شده است و بهترین طراحان در طراحی آن دست داشته اند، در سه سایز ارائه شده است.",
    enName: "pant_2r_33_Q",
    categoryNames: ["men-sweatshirt", "men", "fashion"],
    name: "گرم کن حمید",
    price: 10000,
    image: "/images/shoes.jpg",
    address: "/productdetail",
  },
  {
    id: 7,
    brandName: "Salamon",
    shortDescription: "ست گرم کن آدیداس",specifics:[{key:"طرح",value:"سینایی"},{key:"کشور",value:"ایران"}],
    description:
      "در تولید این محصول از الیاف با کیفیت استفاده شده است و بهترین طراحان در طراحی آن دست داشته اند، در سه سایز ارائه شده است.",
    enName: "pant_2r_33_Q",
    categoryNames: ["men-shoes-sport", "men-shoes", "men", "fashion"],
    name: "کفش رضا",
    price: 10000,
    image: "/images/shoes.jpg",
    address: "/productdetail",
  },
  {
    id: 8,
    brandName: "Kikiriki",
    shortDescription: "ست گرم کن آدیداس",specifics:[{key:"طرح",value:"سینایی"},{key:"کشور",value:"ایران"}],
    description:
      "در تولید این محصول از الیاف با کیفیت استفاده شده است و بهترین طراحان در طراحی آن دست داشته اند، در سه سایز ارائه شده است.",
    enName: "pant_2r_33_Q",
    categoryNames: ["men-shoes-edari", "men-shoes", "men", "fashion"],
    name: "کفش رضا",
    price: 10000,
    image: "/images/shoes.jpg",
    address: "/productdetail",
  },
  {
    id: 9,
    brandName: "Adidas",
    shortDescription: "ست گرم کن آدیداس",specifics:[{key:"طرح",value:"سینایی"},{key:"کشور",value:"ایران"}],
    description:
      "در تولید این محصول از الیاف با کیفیت استفاده شده است و بهترین طراحان در طراحی آن دست داشته اند، در سه سایز ارائه شده است.",
    enName: "pant_2r_33_Q",
    categoryNames: ["men-shoes-sport", "men-shoes", "men", "fashion"],
    name: "کفش آدیداس",
    price: 10000,
    image: "/images/shoes.jpg",
    address: "/productdetail",
  },
  {
    id: 10,
    brandName: "Adidas",
    shortDescription: "ست گرم کن آدیداس",specifics:[{key:"طرح",value:"سینایی"},{key:"کشور",value:"ایران"}],
    description:
      "در تولید این محصول از الیاف با کیفیت استفاده شده است و بهترین طراحان در طراحی آن دست داشته اند، در سه سایز ارائه شده است.",
    enName: "pant_2r_33_Q",
    categoryNames: ["high-heels", "women-shoes", "women", "fashion"],
    name: "کفش مریم",
    price: 10000,
    image: "/images/shoes.jpg",
    address: "/productdetail",
  },
  {
    id: 11,
    brandName: "AberCrombi",
    shortDescription: "ست گرم کن آدیداس",specifics:[{key:"طرح",value:"سینایی"},{key:"کشور",value:"ایران"}],
    description:
      "در تولید این محصول از الیاف با کیفیت استفاده شده است و بهترین طراحان در طراحی آن دست داشته اند، در سه سایز ارائه شده است.",
    enName: "pant_2r_33_Q",
    categoryNames: ["flat-shoes", "women-shoes", "women", "fashion"],
    name: "کفش نگار",
    price: 10000,
    image: "/images/shoes.jpg",
    address: "/productdetail",
  },
  {
    id: 12,
    brandName: "Ribak",
    shortDescription: "ست گرم کن آدیداس",specifics:[{key:"طرح",value:"سینایی"},{key:"کشور",value:"ایران"}],
    description:
      "در تولید این محصول از الیاف با کیفیت استفاده شده است و بهترین طراحان در طراحی آن دست داشته اند، در سه سایز ارائه شده است.",
    enName: "pant_2r_33_Q",
    categoryNames: ["women-skirt-monokrom", "women-skirt", "women", "fashion"],
    name: "دامن ماکسی",
    price: 10000,
    image: "/images/shoes.jpg",
    address: "/productdetail",
  },
  {
    id: 13,
    brandName: "Mel&Moj",
    shortDescription: "ست گرم کن آدیداس",specifics:[{key:"طرح",value:"سینایی"},{key:"کشور",value:"ایران"}],
    description:
      "در تولید این محصول از الیاف با کیفیت استفاده شده است و بهترین طراحان در طراحی آن دست داشته اند، در سه سایز ارائه شده است.",
    enName: "pant_2r_33_Q",
    categoryNames: ["women-skirt-colorful", "women-skirt", "women", "fashion"],
    name: "دامن مجلسی",
    price: 10000,
    image: "/images/shoes.jpg",
    address: "/productdetail",
  },
  {
    id: 14,
    brandName: "AberCrombi",
    shortDescription: "ست گرم کن آدیداس",specifics:[{key:"طرح",value:"سینایی"},{key:"کشور",value:"ایران"}],
    description:
      "در تولید این محصول از الیاف با کیفیت استفاده شده است و بهترین طراحان در طراحی آن دست داشته اند، در سه سایز ارائه شده است.",
    enName: "pant_2r_33_Q",
    categoryNames: ["kids-socks", "kids", "fashion"],
    name: "جوراب کویر",
    price: 10000,
    image: "/images/shoes.jpg",
    address: "/productdetail",
  },
  {
    id: 15,
    brandName: "Ribak",
    shortDescription: "ست گرم کن آدیداس",specifics:[{key:"طرح",value:"سینایی"},{key:"کشور",value:"ایران"}],
    description:
      "در تولید این محصول از الیاف با کیفیت استفاده شده است و بهترین طراحان در طراحی آن دست داشته اند، در سه سایز ارائه شده است.",
    enName: "pant_2r_33_Q",
    categoryNames: ["kids-sport-set", "kids", "fashion"],
    name: "گرم کن ریباک",
    price: 10000,
    image: "/images/shoes.jpg",
    address: "/productdetail",
  },
  {
    id: 16,
    brandName: "Tommy",
    shortDescription: "ست گرم کن آدیداس",specifics:[{key:"طرح",value:"سینایی"},{key:"کشور",value:"ایران"}],
    description:
      "در تولید این محصول از الیاف با کیفیت استفاده شده است و بهترین طراحان در طراحی آن دست داشته اند، در سه سایز ارائه شده است.",
    enName: "pant_2r_33_Q",
    categoryNames: ["kids-sport-set", "kids", "fashion"],
    name: "ست ورزشی امیر",
    price: 10000,
    image: "/images/shoes.jpg",
    address: "/productdetail",
  },
  {
    id: 17,
    brandName: "Ribak",
    shortDescription: "ست گرم کن آدیداس",specifics:[{key:"طرح",value:"سینایی"},{key:"کشور",value:"ایران"}],
    description:
      "در تولید این محصول از الیاف با کیفیت استفاده شده است و بهترین طراحان در طراحی آن دست داشته اند، در سه سایز ارائه شده است.",
    enName: "pant_2r_33_Q",
    categoryNames: ["kids-socks", "kids", "fashion"],
    name: "جوراب ساده",
    price: 10000,
    image: "/images/shoes.jpg",
    address: "/productdetail",
  },
  {
    id: 18,
    brandName: "Tommy",
    shortDescription: "ست گرم کن آدیداس",specifics:[{key:"طرح",value:"سینایی"},{key:"کشور",value:"ایران"}],
    description:
      "در تولید این محصول از الیاف با کیفیت استفاده شده است و بهترین طراحان در طراحی آن دست داشته اند، در سه سایز ارائه شده است.",
    enName: "pant_2r_33_Q",
    categoryNames: ["kids-kapshen", "kids", "fashion"],
    name: "کاپشن",
    price: 10000,
    image: "/images/shoes.jpg",
    address: "/productdetail",
  },
  {
    id: 19,
    brandName: "AberCrombi",
    shortDescription: "ست گرم کن آدیداس",specifics:[{key:"طرح",value:"سینایی"},{key:"کشور",value:"ایران"}],
    description:
      "در تولید این محصول از الیاف با کیفیت استفاده شده است و بهترین طراحان در طراحی آن دست داشته اند، در سه سایز ارائه شده است.",
    enName: "pant_2r_33_Q",
    categoryNames: ["kids-kapshen", "kids", "fashion"],
    name: "کاپشن ورزشی",
    price: 10000,
    image: "/images/shoes.jpg",
    address: "/productdetail",
  },
  {
    id: 20,
    brandName: "Salamon",
    shortDescription: "ست گرم کن آدیداس",specifics:[{key:"طرح",value:"سینایی"},{key:"کشور",value:"ایران"}],
    description:
      "در تولید این محصول از الیاف با کیفیت استفاده شده است و بهترین طراحان در طراحی آن دست داشته اند، در سه سایز ارائه شده است.",
    enName: "pant_2r_33_Q",
    categoryNames: ["kids-shirt", "kids", "fashion"],
    name: "بلوز بچه گانه",
    price: 10000,
    image: "/images/shoes.jpg",
    address: "/productdetail",
  },
];

export const brands = [
  { id: 1, englishName: "Ribak", name: "ریباک" },
  { id: 2, englishName: "Adidas", name: "آدیداس" },
  { id: 3, englishName: "Puma", name: "پوما" },
  { id: 4, englishName: "Salamon", name: "سالامون" },
  { id: 5, englishName: "Tommy", name: "تامی" },
  { id: 6, englishName: "Mel&Moj", name: "مل اند موژ" },
  { id: 7, englishName: "AberCrombi", name: "ابرکرمبی" },
  { id: 8, englishName: "Kikiriki", name: "کیکی راکی" },
];

export const user={
  id:123,name:"آوینا",lastName:"طاها", phone:"09128150525"
}

export const addresses=[
  {id:1,userId:123,city:"Tehran",avenue:"ValiAsr"},
{id:2,userId:123,city:"Tehran",avenue:"Arjantin"}
]
